services:

  postgres:
    image: postgres:16
    container_name: server-ms-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: server-ms
